In [1]:
from fastai.collab import CollabDataBunch, collab_learner, load_learner

import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split

import data_loader

In [2]:
reviews, num_vis = data_loader.get_iteractions(recipes=25000, size=50000)
train_data, valid = train_test_split(reviews, test_size=0.2)

train, valid, num_vis = data_loader.splitter(reviews)

In [3]:
train_data.head()

,user_id,recipe_id,date,rating,review
156701,240552,222959,2008-05-03,5,Yummy asparagus! I just sprinkled dressing on...
189631,8688,214533,2007-05-12,5,It's too bad there aren't more stars to award ...
18907,238496,195274,2007-06-14,5,I chose to use regular butter for this dish bu...
792276,43083,275011,2010-02-28,4,This was tasty! I loved the hazelnut w/ the ba...
1039576,30435,63812,2006-07-13,5,What I love about this recipe is I can leave o...

In [9]:
from fastai.collab import CollabDataBunch, collab_learner, load_learner

data = CollabDataBunch.from_df(reviews, user_name='user_id', item_name='recipe_id', rating_name='rating', valid_pct=0.2 )
learner = collab_learner(data, n_factors=40, y_range=[0,5.5], wd=1e-1)

learner.fit_one_cycle(20, 5e-3, wd=0.1)

In [30]:
learner.export('Data/fastai-colab.pkl')