In [1]:
import pandas as pd
import numpy as np
import ast
import re
import os

In [2]:
def segregate(x):
    minutes = 0;
    x = x.strip()
    tokens = x.split(" ")
    for i in range(len(tokens)):
        token = tokens[i].strip()
        if i%2 != 0:
            if token == "hr":
                minutes += int(tokens[i-1].strip()) * 60
            elif token == "mins":
                minutes += int(tokens[i-1].strip())
    return str(minutes)


def process_time(input_df):
    time_taken = input_df.copy()
    time_taken['minutes'] = time_taken['minutes'].astype(str).apply(segregate).astype('int64')
    return time_taken

Read the recipe Datasets and display

In [34]:
AllRecipes_recipes = pd.read_csv("temp/full_allrecipes.csv")
AllRecipes_recipes = process_time(AllRecipes_recipes)
display(AllRecipes_recipes.dtypes)
display(AllRecipes_recipes)

name              object
id                 int64
minutes            int64
contributor_id    object
nutrition         object
n_steps            int64
steps             object
ingredients       object
n_ingredients      int64
dtype: object

,name,id,minutes,contributor_id,nutrition,n_steps,steps,ingredients,n_ingredients
0,Mom's Spiced Eggnog Pancakes,245290,15,Dutchgirl,"['7.2', '33', '0.9', '5.5', '13.2', '4.3', '84...",3,"['Whisk flour, baking powder, salt, nutmeg, an...","['all purpose flour', 'baking powder', 'salt',...",10
1,Summer Minestrone Salad,280605,35,Bear Creek,"['7.6', '39.5', '6.4', '5.6', '1.3', '0.1', '1...",4,['Bring water to a boil. Stir in soup mix and ...,"['ear reek inestrone oup ix', 'water', 'reen i...",7
2,Curry Orange Swai,272454,60,CAMILLEELISE,"['17.6', '11', '0.7', '6.2', '11.1', '2.3', '5...",4,['Lay fish in a glass dish; season both sides ...,"['fillets swai fish', 'ground black pepper to ...",9
3,Chanterelle Mushroom Soup,268025,50,LorraineMargaret,"['6', '21.8', '3.4', '3.9', '8.7', '3.2', '10....",3,['Heat butter and oil in a heavy-bottomed pot ...,"['butter', 'olive oil', 'onion finely chopped'...",12
4,Vegan Gingerbread Scones,245263,50,Kameron,"['1.8', '20.3', '1.1', '6.9', '7.4', '6', '2.6...",6,['Preheat oven to 300 degrees F (150 degrees C...,"['orange', 'water as needed', 'chia seeds', 'b...",15
...,...,...,...,...,...,...,...,...,...
7381,Mango Jam,142747,60,RADHIKA GHATAGE,"['0.2', '18.9', '0.7', '18.1', '0.1', '289.4',...",3,"['Boil, steam, or microwave the whole mangoes ...","['pounds ripe mangoes', 'white sugar', 'water'...",4
7382,Bauernomlett (Farmer's Omelet),142748,35,anjamizner,"['17.8', '37.9', '4.7', '2.2', '14.6', '5.3', ...",3,['Place potatoes in a saucepan covered by ligh...,"['butter', 'bacon cut into pieces', 'potatoes'...",5
7383,Refrigerator Pickles,14275,75,GARYR,"['0.2', '11.2', '0.3', '10.3', '0.1', '31.1', ...",1,['Mix the cucumbers and salt and let sit for o...,"['cucumbers peeled and thinly sliced', 'salt',...",7
7384,Easy German Potato Salad,142751,70,anjamizner,"['6.2', '51.9', '6.5', '3.2', '14.9', '2.3', '...",2,['Place potatoes in a large saucepan or Dutch ...,"['potatoes', 'cucumber thinly sliced', 'mayonn...",4
7385,Spinach with Apples and Pine Nuts,142754,15,Bethany S,"['3.2', '8.4', '2.6', '4', '9.3', '1.3', '6677...",2,['Heat the olive oil in a large skillet or wok...,"['olive oil', 'cloves garlic slivered', 'pine ...",6

In [35]:
DamnDelicious_recipes = pd.read_csv("temp/damn_delicious_recipes.csv")
DamnDelicious_recipes = DamnDelicious_recipes.drop(['ratings','ratings_count','tags','submitted'], axis=1)
DamnDelicious_recipes['contributor_id'] = "Unknown"
display(DamnDelicious_recipes.dtypes)
display(DamnDelicious_recipes)

id                 int64
name              object
minutes            int64
n_ingredients      int64
ingredients       object
n_steps            int64
steps             object
nutrition         object
contributor_id    object
dtype: object

,id,name,minutes,n_ingredients,ingredients,n_steps,steps,nutrition,contributor_id
0,0,Vanilla Glazed Apple Cinnamon Muffins,30,13,"['all purpose flour', 'baking powder', 'cinnam...",7,['Preheat oven to 350 degrees F. Coat a standa...,[],Unknown
1,1,Bacon Wrapped Asparagus,30,10,"['unsalted butter, melted', 'brown sugar, pack...",7,['Preheat oven to 400 degrees F. Lightly oil a...,"['318.9', '28.2', '13.0', '48.4', '69.4', '15....",Unknown
2,2,Prosciutto Wrapped Asparagus,15,3,"['sliced prosciutto, halved horizontally', 'po...",3,"['Working one at a time, wrap halved prosciutt...",[],Unknown
3,3,Asparagus Tart with Balsamic Reduction,35,7,"['frozen puff pastry, thawed, cut into squares...",6,['Preheat oven to 400 degrees F. Line a baking...,[],Unknown
4,4,Whole Wheat Veggie Flatbread Pizza,20,6,"['wheat middle eastern flatbreads', 'marinara ...",4,['Preheat oven to 375 degrees F. Line a baking...,[],Unknown
...,...,...,...,...,...,...,...,...,...
377,377,Leftover Thanksgiving Turkey Pesto Panini,15,7,"['olive oil', 'of french bread, cut into equal...",3,['Heat olive oil in a grill pan over medium-hi...,[],Unknown
378,378,Sheet Pan Zucchini Parmesan,40,9,"['panko*', 'freshly grated parmesan cheese', '...",7,['Preheat oven to 400 degrees F. Lightly oil a...,[],Unknown
379,379,Zucchini Parmesan Foil Packets,25,8,"['unsalted butter, melted', 'freshly grated pa...",5,['PREHEAT a gas or charcoal grill over high he...,"['163.6', '13.9', '8.5', '35.0', '124.5', '6.9...",Unknown
380,380,Zucchini Alfredo,30,11,"['unsalted butter, divided', 'pound sized zu...",5,['Melt 1 tablespoon butter in a saucepan over ...,"['203.6', '14.2', '8.3', '39.5', '168.5', '12....",Unknown
381,381,Zucchini Tots,40,14,"['zucchini, shredded', 'salt', 'carrots, peele...",6,['Preheat oven to 400 degrees F. Lightly oil a...,"['88.6', '4.9', '2', '67.5', '119.1', '8.3', '...",Unknown

In [36]:
FoodCom_recipes = pd.read_csv("temp/full_food.csv")
FoodCom_recipes = FoodCom_recipes.rename(columns={"n_step":"n_steps"})
FoodCom_recipes['minutes'] = FoodCom_recipes['minutes'].fillna(0)
FoodCom_recipes['minutes'] = FoodCom_recipes['minutes'].astype(int)
display(FoodCom_recipes.dtypes)
display(FoodCom_recipes)

name              object
id                 int64
minutes            int64
contributor_id    object
nutrition         object
n_steps            int64
steps             object
ingredients       object
n_ingredients      int64
dtype: object

,name,id,minutes,contributor_id,nutrition,n_steps,steps,ingredients,n_ingredients
0,Tuna Kabobs,99998,25,Lorac,"['219.5', '7233', '8.112', '1.99', '53.917', '...",4,"['Preheat grill to medium high.', 'Combine soy...","['soy sauce', 'rice vinegar', 'toasted sesame ...",7
1,South Beach Diet Balsamic Vinaigrette,99996,5,papergoddess,"['142.7', '12991', '14.422', '29', '00', '120....",3,['Combine all ingredients in a jar or containe...,"['extra virgin olive oil', 'balsamic vinegar',...",6
2,All to Myself Cheesecake,99995,45,Claudia Dawn,"['268.5', '16963', '18.828', '9.748', '72.724'...",7,"['Beat cream cheese, sugar, vanilla and eggs t...","['reo cookies tops separated from bottoms', 'c...",7
3,Feta Potatoes,99994,45,Dawnab,"['264.3', '12648', '14.121', '7.838', '43.614'...",3,"['Preheat oven to 375.', 'combine all ingredie...",['frozen cubed hash brown potatoes southern st...,5
4,Shish Kabob Marinade,99992,125,jenjill,"['75.8', '01', '0.10', '00', '00', '117348', '...",4,"['Mix all ingredients together.', 'Add meat (c...","['soy sauce', 'ketchup', 'sugar', 'ginger', 'g...",5
...,...,...,...,...,...,...,...,...,...
499995,pumpkin bar,13465,25,Debra Stuart,"['7540.5', '298740', '331.9510', '87435', '109...",6,"['Beat: Eggs, oil, pumpkin.', 'Mix together: f...","['eggs', 'oil', 'pumpkin', 'flour', 'flour', '...",16
499996,Strawberry Mille Feuille,134649,35,Fairy Nuff,"['638.6', '40363', '44.868', '18.190', '68.522...",12,"['Preheat oven to 220C (425F).', 'Roll out pas...","['puff pastry thawed', 'fresh strawberries', '...",6
499997,Cuban Bread,134648,168,Dawn1,"['134.9', '33', '0.40', '0.10', '00', '278.911...",16,"['Place the water in mixing bowl.', 'Mix all o...","['water', 'instant yeast', 'bread flour', 'sal...",5
499998,Hungarian Dessert Cake,134646,34,Fairy Nuff,"['610.1', '32754', '36.455', '16.482', '44.214...",5,['Place one crepe or pancake on a greased baki...,"['crepes pancakes', 'apricot jam plum jam', 'd...",9
499999,Maple Pecan Fudge,134641,30,Fairy Nuff,"['115', '4742', '5.38', '2.311', '12.14', '23....",8,"['Line an 8 inch square baking dish with foil,...","['pecans chopped', 'brown sugar packed', 'whip...",7

In [37]:
FoodNetwork_recipes = pd.read_csv("temp/food_network_recipes.csv")
FoodNetwork_recipes = FoodNetwork_recipes.drop(['categories','servings'], axis=1)
FoodNetwork_recipes.columns = ['id','name','minutes','ingredients','steps','n_steps','n_ingredients']
FoodNetwork_recipes['contributor_id'] = "Unknown"
FoodNetwork_recipes['nutrition'] = "[]"
display(FoodNetwork_recipes.dtypes)
display(FoodNetwork_recipes)

/var/folders/5b/0vdy5nmd29z46fdb__gqk64h0000gn/T/ipykernel_25504/1615932747.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  FoodNetwork_recipes = pd.read_csv("temp/food_network_recipes.csv")

id                object
name              object
minutes            int64
ingredients       object
steps             object
n_steps            int64
n_ingredients      int64
contributor_id    object
nutrition         object
dtype: object

,id,name,minutes,ingredients,steps,n_steps,n_ingredients,contributor_id,nutrition
0,1940225,"""We Need to Talk"" Chocolate Pizza",10,"['recipe basic pizza dough, recipe follows', '...","['Preheat oven to 400 degrees F.', 'After baki...",15,13,Unknown,[]
1,8613916,"""What You Got"" Meatloaf on the Grill",80,"['ketchup', 'light brown sugar', 'worcestershi...","['For the glaze: In a medium bowl, add the ket...",9,20,Unknown,[]
2,2085413,"""What am I...?"" Chopped Liver with Schmaltz Fr...",40,"['reserved skin from chicken, about', 'onion, ...","['In a skillet over medium heat, saute the chi...",2,6,Unknown,[]
3,3414490,"""Who Will Love Me As I Yam?"" Pie",80,"['bourbon marshmallows:', 'nonstick cooking sp...","[""For the bourbon marshmallows: Spray a 9-by-1...",8,26,Unknown,[]
4,1947492,(Web Exclusive) Round 2 Recipe: Bean Chili Que...,22,"['flour tortillas', 'shredded jack cheese', 'b...",['Heat a large skillet over medium-high heat.'...,4,13,Unknown,[]
...,...,...,...,...,...,...,...,...,...
75537,1938900,Myrna's Toasted Coconut-Chocolate Bars,50,"['heaping sugar', 'scant egg whites from abou...",['Heat the oven to 350 degrees F. Mix the suga...,2,5,Unknown,[]
75538,1940002,Mystery Meat Loaf,100,"['pounds ground round beef percent lean', 'se...",['Preheat oven to 350 degrees. In a large bowl...,1,7,Unknown,[]
75539,1910928,Mystery Mocha Cake,60,"['unsweetened chocolate', 'butter', 'sugar', '...","['Preheat oven to 350 degrees F.', 'Melt the c...",2,11,Unknown,[]
75540,2593846,Mystery Rolls,20,"['stick butter', 'crumbled blue cheese', 'fl...","['Preheat the oven to 350 degrees F.', 'Put th...",4,3,Unknown,[]
75541,2103110,Mystery of the Orient,240,"['pounds bittersweet chocolate, tempered', 'wh...",['Make the base: Use flexible aluminum strips ...,3,7,Unknown,[]

To avoid recipe_id mismatch, merging the dataset with caution

In [38]:
recipe_id_list = FoodCom_recipes['id'].tolist()
def get_count(num):
    for count in range(num, (FoodCom_recipes['id'].max())):
        if count not in recipe_id_list:
            recipe_id_list.append(count)
            return int(count);

In [39]:
count = 0
for index, row in DamnDelicious_recipes.iterrows():
    count = get_count(count)
    DamnDelicious_recipes.at[index,'recipe_id'] = count
DamnDelicious_recipes['recipe_id'] = DamnDelicious_recipes['recipe_id'].astype("int64")
display(DamnDelicious_recipes)

,id,name,minutes,n_ingredients,ingredients,n_steps,steps,nutrition,contributor_id,recipe_id
0,0,Vanilla Glazed Apple Cinnamon Muffins,30,13,"['all purpose flour', 'baking powder', 'cinnam...",7,['Preheat oven to 350 degrees F. Coat a standa...,[],Unknown,0
1,1,Bacon Wrapped Asparagus,30,10,"['unsalted butter, melted', 'brown sugar, pack...",7,['Preheat oven to 400 degrees F. Lightly oil a...,"['318.9', '28.2', '13.0', '48.4', '69.4', '15....",Unknown,1
2,2,Prosciutto Wrapped Asparagus,15,3,"['sliced prosciutto, halved horizontally', 'po...",3,"['Working one at a time, wrap halved prosciutt...",[],Unknown,2
3,3,Asparagus Tart with Balsamic Reduction,35,7,"['frozen puff pastry, thawed, cut into squares...",6,['Preheat oven to 400 degrees F. Line a baking...,[],Unknown,3
4,4,Whole Wheat Veggie Flatbread Pizza,20,6,"['wheat middle eastern flatbreads', 'marinara ...",4,['Preheat oven to 375 degrees F. Line a baking...,[],Unknown,4
...,...,...,...,...,...,...,...,...,...,...
377,377,Leftover Thanksgiving Turkey Pesto Panini,15,7,"['olive oil', 'of french bread, cut into equal...",3,['Heat olive oil in a grill pan over medium-hi...,[],Unknown,1069
378,378,Sheet Pan Zucchini Parmesan,40,9,"['panko*', 'freshly grated parmesan cheese', '...",7,['Preheat oven to 400 degrees F. Lightly oil a...,[],Unknown,1070
379,379,Zucchini Parmesan Foil Packets,25,8,"['unsalted butter, melted', 'freshly grated pa...",5,['PREHEAT a gas or charcoal grill over high he...,"['163.6', '13.9', '8.5', '35.0', '124.5', '6.9...",Unknown,1071
380,380,Zucchini Alfredo,30,11,"['unsalted butter, divided', 'pound sized zu...",5,['Melt 1 tablespoon butter in a saucepan over ...,"['203.6', '14.2', '8.3', '39.5', '168.5', '12....",Unknown,1072
381,381,Zucchini Tots,40,14,"['zucchini, shredded', 'salt', 'carrots, peele...",6,['Preheat oven to 400 degrees F. Lightly oil a...,"['88.6', '4.9', '2', '67.5', '119.1', '8.3', '...",Unknown,1074

In [40]:
for index, row in AllRecipes_recipes.iterrows():
    count = get_count(count)
    AllRecipes_recipes.at[index,'recipe_id'] = count
AllRecipes_recipes['recipe_id'] = AllRecipes_recipes['recipe_id'].astype("int64")
display(AllRecipes_recipes)

,name,id,minutes,contributor_id,nutrition,n_steps,steps,ingredients,n_ingredients,recipe_id
0,Mom's Spiced Eggnog Pancakes,245290,15,Dutchgirl,"['7.2', '33', '0.9', '5.5', '13.2', '4.3', '84...",3,"['Whisk flour, baking powder, salt, nutmeg, an...","['all purpose flour', 'baking powder', 'salt',...",10,1075
1,Summer Minestrone Salad,280605,35,Bear Creek,"['7.6', '39.5', '6.4', '5.6', '1.3', '0.1', '1...",4,['Bring water to a boil. Stir in soup mix and ...,"['ear reek inestrone oup ix', 'water', 'reen i...",7,1076
2,Curry Orange Swai,272454,60,CAMILLEELISE,"['17.6', '11', '0.7', '6.2', '11.1', '2.3', '5...",4,['Lay fish in a glass dish; season both sides ...,"['fillets swai fish', 'ground black pepper to ...",9,1077
3,Chanterelle Mushroom Soup,268025,50,LorraineMargaret,"['6', '21.8', '3.4', '3.9', '8.7', '3.2', '10....",3,['Heat butter and oil in a heavy-bottomed pot ...,"['butter', 'olive oil', 'onion finely chopped'...",12,1079
4,Vegan Gingerbread Scones,245263,50,Kameron,"['1.8', '20.3', '1.1', '6.9', '7.4', '6', '2.6...",6,['Preheat oven to 300 degrees F (150 degrees C...,"['orange', 'water as needed', 'chia seeds', 'b...",15,1080
...,...,...,...,...,...,...,...,...,...,...
7381,Mango Jam,142747,60,RADHIKA GHATAGE,"['0.2', '18.9', '0.7', '18.1', '0.1', '289.4',...",3,"['Boil, steam, or microwave the whole mangoes ...","['pounds ripe mangoes', 'white sugar', 'water'...",4,100024
7382,Bauernomlett (Farmer's Omelet),142748,35,anjamizner,"['17.8', '37.9', '4.7', '2.2', '14.6', '5.3', ...",3,['Place potatoes in a saucepan covered by ligh...,"['butter', 'bacon cut into pieces', 'potatoes'...",5,100025
7383,Refrigerator Pickles,14275,75,GARYR,"['0.2', '11.2', '0.3', '10.3', '0.1', '31.1', ...",1,['Mix the cucumbers and salt and let sit for o...,"['cucumbers peeled and thinly sliced', 'salt',...",7,100026
7384,Easy German Potato Salad,142751,70,anjamizner,"['6.2', '51.9', '6.5', '3.2', '14.9', '2.3', '...",2,['Place potatoes in a large saucepan or Dutch ...,"['potatoes', 'cucumber thinly sliced', 'mayonn...",4,100027
7385,Spinach with Apples and Pine Nuts,142754,15,Bethany S,"['3.2', '8.4', '2.6', '4', '9.3', '1.3', '6677...",2,['Heat the olive oil in a large skillet or wok...,"['olive oil', 'cloves garlic slivered', 'pine ...",6,100028

In [41]:
k = FoodCom_recipes['id'].max()+1
for index, row in FoodNetwork_recipes.iterrows():
    FoodNetwork_recipes.at[index,'recipe_id'] = k
    recipe_id_list.append(k)
    k = k+1
FoodNetwork_recipes['recipe_id'] = FoodNetwork_recipes['recipe_id'].astype("int64")
display(FoodNetwork_recipes)

,id,name,minutes,ingredients,steps,n_steps,n_ingredients,contributor_id,nutrition,recipe_id
0,1940225,"""We Need to Talk"" Chocolate Pizza",10,"['recipe basic pizza dough, recipe follows', '...","['Preheat oven to 400 degrees F.', 'After baki...",15,13,Unknown,[],542797
1,8613916,"""What You Got"" Meatloaf on the Grill",80,"['ketchup', 'light brown sugar', 'worcestershi...","['For the glaze: In a medium bowl, add the ket...",9,20,Unknown,[],542798
2,2085413,"""What am I...?"" Chopped Liver with Schmaltz Fr...",40,"['reserved skin from chicken, about', 'onion, ...","['In a skillet over medium heat, saute the chi...",2,6,Unknown,[],542799
3,3414490,"""Who Will Love Me As I Yam?"" Pie",80,"['bourbon marshmallows:', 'nonstick cooking sp...","[""For the bourbon marshmallows: Spray a 9-by-1...",8,26,Unknown,[],542800
4,1947492,(Web Exclusive) Round 2 Recipe: Bean Chili Que...,22,"['flour tortillas', 'shredded jack cheese', 'b...",['Heat a large skillet over medium-high heat.'...,4,13,Unknown,[],542801
...,...,...,...,...,...,...,...,...,...,...
75537,1938900,Myrna's Toasted Coconut-Chocolate Bars,50,"['heaping sugar', 'scant egg whites from abou...",['Heat the oven to 350 degrees F. Mix the suga...,2,5,Unknown,[],618334
75538,1940002,Mystery Meat Loaf,100,"['pounds ground round beef percent lean', 'se...",['Preheat oven to 350 degrees. In a large bowl...,1,7,Unknown,[],618335
75539,1910928,Mystery Mocha Cake,60,"['unsweetened chocolate', 'butter', 'sugar', '...","['Preheat oven to 350 degrees F.', 'Melt the c...",2,11,Unknown,[],618336
75540,2593846,Mystery Rolls,20,"['stick butter', 'crumbled blue cheese', 'fl...","['Preheat the oven to 350 degrees F.', 'Put th...",4,3,Unknown,[],618337
75541,2103110,Mystery of the Orient,240,"['pounds bittersweet chocolate, tempered', 'wh...",['Make the base: Use flexible aluminum strips ...,3,7,Unknown,[],618338

## Adding All Four Datasets to One.

In [49]:
FoodCom_recipes['recipe_id'] = FoodCom_recipes['id']

In [65]:
full_recipes = pd.concat([FoodCom_recipes, DamnDelicious_recipes, AllRecipes_recipes, FoodNetwork_recipes], ignore_index=True)
full_recipes['id'] = full_recipes['recipe_id']
full_recipes = full_recipes.drop(['recipe_id'], axis=1)
full_recipes = full_recipes[['name', 'id', 'minutes', 'contributor_id', 'nutrition', 'n_steps', 'steps', 'ingredients', 'n_ingredients']]

In [66]:
display(full_recipes)

,name,id,minutes,contributor_id,nutrition,n_steps,steps,ingredients,n_ingredients
0,Tuna Kabobs,99998,25,Lorac,"['219.5', '7233', '8.112', '1.99', '53.917', '...",4,"['Preheat grill to medium high.', 'Combine soy...","['soy sauce', 'rice vinegar', 'toasted sesame ...",7
1,South Beach Diet Balsamic Vinaigrette,99996,5,papergoddess,"['142.7', '12991', '14.422', '29', '00', '120....",3,['Combine all ingredients in a jar or containe...,"['extra virgin olive oil', 'balsamic vinegar',...",6
2,All to Myself Cheesecake,99995,45,Claudia Dawn,"['268.5', '16963', '18.828', '9.748', '72.724'...",7,"['Beat cream cheese, sugar, vanilla and eggs t...","['reo cookies tops separated from bottoms', 'c...",7
3,Feta Potatoes,99994,45,Dawnab,"['264.3', '12648', '14.121', '7.838', '43.614'...",3,"['Preheat oven to 375.', 'combine all ingredie...",['frozen cubed hash brown potatoes southern st...,5
4,Shish Kabob Marinade,99992,125,jenjill,"['75.8', '01', '0.10', '00', '00', '117348', '...",4,"['Mix all ingredients together.', 'Add meat (c...","['soy sauce', 'ketchup', 'sugar', 'ginger', 'g...",5
...,...,...,...,...,...,...,...,...,...
583305,Myrna's Toasted Coconut-Chocolate Bars,618334,50,Unknown,[],2,['Heat the oven to 350 degrees F. Mix the suga...,"['heaping sugar', 'scant egg whites from abou...",5
583306,Mystery Meat Loaf,618335,100,Unknown,[],1,['Preheat oven to 350 degrees. In a large bowl...,"['pounds ground round beef percent lean', 'se...",7
583307,Mystery Mocha Cake,618336,60,Unknown,[],2,"['Preheat oven to 350 degrees F.', 'Melt the c...","['unsweetened chocolate', 'butter', 'sugar', '...",11
583308,Mystery Rolls,618337,20,Unknown,[],4,"['Preheat the oven to 350 degrees F.', 'Put th...","['stick butter', 'crumbled blue cheese', 'fl...",3
583309,Mystery of the Orient,618338,240,Unknown,[],3,['Make the base: Use flexible aluminum strips ...,"['pounds bittersweet chocolate, tempered', 'wh...",7

In [67]:
display(full_recipes[full_recipes['id'].duplicated(keep=False)])

Empty DataFrame
Columns: [name, id, minutes, contributor_id, nutrition, n_steps, steps, ingredients, n_ingredients]
Index: []

## Add Reviews to one Dataframe

In [91]:
AllRecipes_reviews = pd.read_csv("temp/full_allrecipes_reviews.csv")
AllRecipes_reviews['date'] = "2022-01-01T00:00:00+00:00"
AllRecipes_reviews['rating'] = AllRecipes_reviews['rating'].astype('float64')
display(AllRecipes_reviews.dtypes)
display(AllRecipes_reviews)

user_id       object
recipe_id      int64
rating       float64
review        object
date          object
dtype: object

,user_id,recipe_id,rating,review,date
0,sanzoe,245290,2.0,I had high hopes for these but these were not ...,2022-01-01T00:00:00+00:00
1,ruthncls,280605,1.0,Strange recipe as written. It was more like a ...,2022-01-01T00:00:00+00:00
2,Soup Loving Nicole,272454,4.0,Made as written and this turned out pretty goo...,2022-01-01T00:00:00+00:00
3,youngheart,268025,4.0,It was very good and easy to make.,2022-01-01T00:00:00+00:00
4,emily11421,245263,5.0,I live in a small town and don't have immediat...,2022-01-01T00:00:00+00:00
...,...,...,...,...,...
416082,Karen C Leslie,143002,5.0,We drained 2 cans of mixed vegetables in place...,2022-01-01T00:00:00+00:00
416083,Lexi Galantino,143002,4.0,I doubled the spices (added curry powder) and ...,2022-01-01T00:00:00+00:00
416084,Hannah Bauer,143002,3.0,Needs more flavor.,2022-01-01T00:00:00+00:00
416085,Curt Crosby,143002,5.0,Good stuff!,2022-01-01T00:00:00+00:00
416086,bhoconnor,143002,4.0,"Love the diced little potatoes, they really ma...",2022-01-01T00:00:00+00:00

In [79]:
DamnDelicious_reviews = pd.read_csv("temp/damn_delicious_reviews.csv")
display(DamnDelicious_reviews.dtypes)
display(DamnDelicious_reviews)

user_id       object
recipe_id      int64
date          object
rating       float64
review        object
dtype: object

,user_id,recipe_id,date,rating,review
0,Krystle,0,2016-11-02T13:04:59-07:00,0.0,Totally bummed to make this and find that I on...
1,Jess,0,2022-01-01T00:00:00+00:00,0.0,I absolutely love this recipe! So much so I ad...
2,Rachel,0,2022-01-01T00:00:00+00:00,0.0,Muffins. I. love. Muffins. Maybe itâ€™s the carb...
3,Nicola,0,2014-10-26T14:17:08-07:00,0.0,Did you really mean only half a cup of flour? ...
4,Maria,0,2014-07-12T18:31:09-07:00,0.0,According to the proportions in the recipe how...
...,...,...,...,...,...
22625,Elizabeth,381,2015-08-09T05:27:15-07:00,0.0,Tasty idea for school lunches. Salsa would als...
22626,MONA,381,2015-08-09T04:23:40-07:00,0.0,Thanks for all your great recipes. Am going t...
22627,LOUISE VANDERMAREL,381,2015-08-09T01:20:56-07:00,0.0,"HI Chunga, I love home made snacks, including ..."
22628,Shauna,381,2022-01-01T00:00:00+00:00,0.0,Do you know about how much grated zucchini you...
22629,Averie @ Averie Cooks,381,2022-01-01T00:00:00+00:00,0.0,These look and sound so good! I wish I had a p...

In [92]:
FoodCom_reviews = pd.read_csv("temp/user_interactions.csv")
FoodCom_reviews['date'] = "2022-01-01T00:00:00+00:00"
FoodCom_reviews['rating'] = FoodCom_reviews['rating'].astype('float64')
display(FoodCom_reviews.dtypes)
display(FoodCom_reviews)

user_id        int64
recipe_id      int64
rating       float64
review        object
date          object
dtype: object

,user_id,recipe_id,rating,review,date
0,1509050,99998,5.0,"Substituted cayenne for wasabi, which we hate....",2022-01-01T00:00:00+00:00
1,672182,99998,5.0,Wow - what a great & easy recipe to add to you...,2022-01-01T00:00:00+00:00
2,983557,99996,5.0,I tripled this recipe so id have it on hand fo...,2022-01-01T00:00:00+00:00
3,1402541,99996,5.0,"My husband and I love this Recipe. BUT, when ...",2022-01-01T00:00:00+00:00
4,1114506,99996,5.0,Simple. Fast. Healthy. Tasty.,2022-01-01T00:00:00+00:00
...,...,...,...,...,...
791409,199882,134649,5.0,I made this for the French part of the Tour to...,2022-01-01T00:00:00+00:00
791410,199685,134649,5.0,I made this for the Tour while we were in Fran...,2022-01-01T00:00:00+00:00
791411,836436,134641,4.0,I would classify this as penuche or brown suga...,2022-01-01T00:00:00+00:00
791412,617761,134641,1.0,I made this last night to take to a birthday p...,2022-01-01T00:00:00+00:00
791413,287449,134641,5.0,This fudge is soooo delicious! I am eating way...,2022-01-01T00:00:00+00:00

In [ ]:
display(FoodNetwork_reviews[FoodNetwork_reviews['recipe_id'] == None])

In [100]:
FoodNetwork_reviews = pd.read_csv("temp/food_network_reviews.csv")
FoodNetwork_reviews['date'] = FoodNetwork_reviews['date'].str[:-1]
FoodNetwork_reviews['rating'] = FoodNetwork_reviews['rating'].apply(lambda x: 0 if x == "None" else x)
FoodNetwork_reviews['rating'] = FoodNetwork_reviews['rating'].astype('float64')
display(FoodNetwork_reviews.dtypes)
display(FoodNetwork_reviews)

user_id       object
recipe_id      int64
date          object
rating       float64
review        object
dtype: object

,user_id,recipe_id,date,rating,review
0,Cynthia P.,1940340,2008-08-21T22:14:08.000,5.0,Absolutely delicious...creamed corn without th...
1,lynchgmr,2106689,2013-11-15T01:31:01.000,5.0,"I just made this as part of a ""healthy Thanksg..."
2,Jim Island Girl,2106689,2013-09-22T17:07:50.000,4.0,I did a little substituting (using regular syr...
3,Rachel D.,2106689,2012-11-24T20:58:04.000,5.0,I made this for Thanksgiving this year as I ju...
4,None,2106689,2011-12-27T21:24:26.000,5.0,LOVE LOVE LOVE this recipe!!!! I wanted to hav...
...,...,...,...,...,...
9076,charlieO,2124326,2010-10-21T12:22:43.000,5.0,After watching the Tailgate Warriors I was won...
9077,None,2047697,2014-06-12T20:44:42.000,5.0,"I haven't tried it yet, but I'm curious - it s..."
9078,None,2047697,2012-12-22T08:09:43.000,5.0,We actually have done this every year for many...
9079,djscotec,2047697,2012-01-15T14:07:44.000,5.0,Robert you are a tailgating genius! This is j...
9080,bookpusher700,2047697,2011-11-25T13:01:39.000,5.0,Quick and easy. Having the men do this turkey...

In [101]:
### Generating User id

2099484
2

In [207]:
user_id_list = FoodCom_reviews['user_id'].to_list()
def get_next_idx(count):
    for i in range(count, (FoodCom_reviews['user_id'].max())):
        if i not in user_id_list:
            return i

In [208]:
idx = 0

fn_unique_df = FoodNetwork_reviews['user_id'].unique()
fn_unique_df = pd.DataFrame(data=fn_unique_df, columns=['user_name'])

for index, row in fn_unique_df.iterrows():
    idx = get_next_idx(idx)
    fn_unique_df.at[index,'userid'] = idx
    user_id_list.append(idx)
fn_unique_df['userid'] = fn_unique_df['userid'].astype('int64')

FoodNetwork_reviews_copy = FoodNetwork_reviews.copy()
FoodNetwork_reviews_copy = FoodNetwork_reviews_copy[FoodNetwork_reviews_copy['user_id'].isnull() == False]
FoodNetwork_reviews_copy = FoodNetwork_reviews_copy[FoodNetwork_reviews_copy['user_id'] != "None"]
FoodNetwork_reviews_copy = FoodNetwork_reviews_copy[FoodNetwork_reviews_copy['review'].isnull() == False]

FoodNetwork_reviews_copy = pd.merge(left=FoodNetwork_reviews_copy, right=fn_unique_df, how="left", left_on="user_id", right_on="user_name")
FoodNetwork_reviews_copy['user_id'] = FoodNetwork_reviews_copy['userid']
FoodNetwork_reviews_copy['user_id'] = FoodNetwork_reviews_copy['user_id'].astype('int64')
FoodNetwork_reviews_copy = FoodNetwork_reviews_copy.drop(['userid','user_name'], axis=1)
FoodNetwork_reviews_copy.columns = ['user_id', 'recipeid', 'date', 'rating', 'review']

temp_df = FoodNetwork_recipes[['id', 'recipe_id']].copy()
temp_df = temp_df[temp_df['id'].str.isnumeric() == True]
temp_df['id'] = temp_df['id'].astype('float64').astype('int64')

FoodNetwork_reviews_final= pd.merge(left=FoodNetwork_reviews_copy, right=temp_df, how="left", left_on="recipeid", right_on="id")
FoodNetwork_reviews_final = FoodNetwork_reviews_final[['user_id','recipe_id','date','rating','review']]

display(FoodNetwork_reviews_final)

,user_id,recipe_id,date,rating,review
0,0,604516,2008-08-21T22:14:08.000,5.0,Absolutely delicious...creamed corn without th...
1,1,604520,2013-11-15T01:31:01.000,5.0,"I just made this as part of a ""healthy Thanksg..."
2,3,604520,2013-09-22T17:07:50.000,4.0,I did a little substituting (using regular syr...
3,4,604520,2012-11-24T20:58:04.000,5.0,I made this for Thanksgiving this year as I ju...
4,6,604520,2011-12-26T15:06:05.000,5.0,My daughter suggested I make this for Christma...
...,...,...,...,...,...
7590,18239,604011,2007-03-07T00:54:53.000,5.0,"I know it's a funny comparison, but I really, ..."
7591,18240,604013,2019-10-20T17:03:09.386,1.0,"The recipe is not complete, it doesnâ€™t finish ..."
7592,18241,604013,2010-10-21T12:22:43.000,5.0,After watching the Tailgate Warriors I was won...
7593,18242,604014,2012-01-15T14:07:44.000,5.0,Robert you are a tailgating genius! This is j...
7594,18243,604014,2011-11-25T13:01:39.000,5.0,Quick and easy. Having the men do this turkey...

In [209]:
dd_unique_df = DamnDelicious_reviews['user_id'].unique()
dd_unique_df = pd.DataFrame(data=dd_unique_df, columns=['user_name'])

for index, row in dd_unique_df.iterrows():
    idx = get_next_idx(idx)
    dd_unique_df.at[index,'userid'] = idx
    user_id_list.append(idx)
dd_unique_df['userid'] = dd_unique_df['userid'].astype('int64')

DamnDelicious_reviews_copy = DamnDelicious_reviews.copy()
DamnDelicious_reviews_copy = DamnDelicious_reviews_copy[DamnDelicious_reviews_copy['user_id'].isnull() == False]
DamnDelicious_reviews_copy = DamnDelicious_reviews_copy[DamnDelicious_reviews_copy['user_id'] != "None"]
DamnDelicious_reviews_copy = DamnDelicious_reviews_copy[DamnDelicious_reviews_copy['review'].isnull() == False]

DamnDelicious_reviews_copy = pd.merge(left=DamnDelicious_reviews_copy, right=dd_unique_df, how="left", left_on="user_id", right_on="user_name")
DamnDelicious_reviews_copy['user_id'] = DamnDelicious_reviews_copy['userid']
DamnDelicious_reviews_copy['user_id'] = DamnDelicious_reviews_copy['user_id'].astype('int64')
DamnDelicious_reviews_copy = DamnDelicious_reviews_copy.drop(['userid','user_name'], axis=1)
DamnDelicious_reviews_copy.columns = ['user_id', 'recipeid', 'date', 'rating', 'review']

temp_df = DamnDelicious_recipes[['id', 'recipe_id']].copy()
temp_df['id'] = temp_df['id'].astype('float64').astype('int64')

DamnDelicious_reviews_final = pd.merge(left=DamnDelicious_reviews_copy, right=temp_df, how="left", left_on="recipeid", right_on="id")
DamnDelicious_reviews_final = DamnDelicious_reviews_final[['user_id','recipe_id','date','rating','review']]

display(DamnDelicious_reviews_final)

,user_id,recipe_id,date,rating,review
0,18244,0,2016-11-02T13:04:59-07:00,0.0,Totally bummed to make this and find that I on...
1,18245,0,2022-01-01T00:00:00+00:00,0.0,I absolutely love this recipe! So much so I ad...
2,18246,0,2022-01-01T00:00:00+00:00,0.0,Muffins. I. love. Muffins. Maybe itâ€™s the carb...
3,18247,0,2014-10-26T14:17:08-07:00,0.0,Did you really mean only half a cup of flour? ...
4,18248,0,2014-07-12T18:31:09-07:00,0.0,According to the proportions in the recipe how...
...,...,...,...,...,...
22625,46547,1074,2015-08-09T05:27:15-07:00,0.0,Tasty idea for school lunches. Salsa would als...
22626,68202,1074,2015-08-09T04:23:40-07:00,0.0,Thanks for all your great recipes. Am going t...
22627,68203,1074,2015-08-09T01:20:56-07:00,0.0,"HI Chunga, I love home made snacks, including ..."
22628,47735,1074,2022-01-01T00:00:00+00:00,0.0,Do you know about how much grated zucchini you...
22629,43978,1074,2022-01-01T00:00:00+00:00,0.0,These look and sound so good! I wish I had a p...

In [224]:
ar_unique_df = AllRecipes_reviews['user_id'].unique()
ar_unique_df = pd.DataFrame(data=ar_unique_df, columns=['user_name'])

for index, row in ar_unique_df.iterrows():
    idx = get_next_idx(idx)
    ar_unique_df.at[index,'userid'] = idx
    user_id_list.append(idx)
ar_unique_df['userid'] = ar_unique_df['userid'].astype('int64')

AllRecipes_reviews_copy = AllRecipes_reviews.copy()
AllRecipes_reviews_copy = AllRecipes_reviews_copy[AllRecipes_reviews_copy['user_id'].isnull() == False]
AllRecipes_reviews_copy = AllRecipes_reviews_copy[AllRecipes_reviews_copy['user_id'] != "None"]
AllRecipes_reviews_copy = AllRecipes_reviews_copy[AllRecipes_reviews_copy['review'].isnull() == False]

AllRecipes_reviews_copy = pd.merge(left=AllRecipes_reviews_copy, right=ar_unique_df, how="left", left_on="user_id", right_on="user_name")
AllRecipes_reviews_copy['user_id'] = AllRecipes_reviews_copy['userid']
AllRecipes_reviews_copy['user_id'] = AllRecipes_reviews_copy['user_id'].astype('int64')
AllRecipes_reviews_copy = AllRecipes_reviews_copy.drop(['userid','user_name'], axis=1)
AllRecipes_reviews_copy.columns = ['user_id', 'recipeid', 'rating', 'review', 'date']

temp_df = AllRecipes_recipes[['id', 'recipe_id']].copy()
temp_df['id'] = temp_df['id'].astype('float64').astype('int64')

AllRecipes_reviews_final = pd.merge(left=AllRecipes_reviews_copy, right=temp_df, how="left", left_on="recipeid", right_on="id")
AllRecipes_reviews_final = AllRecipes_reviews_final[['user_id','recipe_id','date','rating','review']]

display(AllRecipes_reviews_final)

,user_id,recipe_id,date,rating,review
0,68204,1075.0,2022-01-01T00:00:00+00:00,2.0,I had high hopes for these but these were not ...
1,68208,1076.0,2022-01-01T00:00:00+00:00,1.0,Strange recipe as written. It was more like a ...
2,68209,1077.0,2022-01-01T00:00:00+00:00,4.0,Made as written and this turned out pretty goo...
3,68211,1079.0,2022-01-01T00:00:00+00:00,4.0,It was very good and easy to make.
4,68215,1080.0,2022-01-01T00:00:00+00:00,5.0,I live in a small town and don't have immediat...
...,...,...,...,...,...
416057,198104,13238.0,2022-01-01T00:00:00+00:00,5.0,We drained 2 cans of mixed vegetables in place...
416058,198105,13238.0,2022-01-01T00:00:00+00:00,4.0,I doubled the spices (added curry powder) and ...
416059,198106,13238.0,2022-01-01T00:00:00+00:00,3.0,Needs more flavor.
416060,198107,13238.0,2022-01-01T00:00:00+00:00,5.0,Good stuff!
416061,198108,13238.0,2022-01-01T00:00:00+00:00,4.0,"Love the diced little potatoes, they really ma..."

In [217]:
FoodCom_reviews_final = FoodCom_reviews.copy()
FoodCom_reviews_final = FoodCom_reviews_final[['user_id','recipe_id','date','rating','review']]

In [225]:
final_reviews_df = pd.concat([FoodCom_reviews_final, DamnDelicious_reviews_final, FoodNetwork_reviews_final, AllRecipes_reviews_final], ignore_index=True)

In [226]:
display(final_reviews_df)

,user_id,recipe_id,date,rating,review
0,1509050,99998.0,2022-01-01T00:00:00+00:00,5.0,"Substituted cayenne for wasabi, which we hate...."
1,672182,99998.0,2022-01-01T00:00:00+00:00,5.0,Wow - what a great & easy recipe to add to you...
2,983557,99996.0,2022-01-01T00:00:00+00:00,5.0,I tripled this recipe so id have it on hand fo...
3,1402541,99996.0,2022-01-01T00:00:00+00:00,5.0,"My husband and I love this Recipe. BUT, when ..."
4,1114506,99996.0,2022-01-01T00:00:00+00:00,5.0,Simple. Fast. Healthy. Tasty.
...,...,...,...,...,...
1237696,198104,13238.0,2022-01-01T00:00:00+00:00,5.0,We drained 2 cans of mixed vegetables in place...
1237697,198105,13238.0,2022-01-01T00:00:00+00:00,4.0,I doubled the spices (added curry powder) and ...
1237698,198106,13238.0,2022-01-01T00:00:00+00:00,3.0,Needs more flavor.
1237699,198107,13238.0,2022-01-01T00:00:00+00:00,5.0,Good stuff!
1237700,198108,13238.0,2022-01-01T00:00:00+00:00,4.0,"Love the diced little potatoes, they really ma..."

In [229]:
if not os.path.exists("../Data/"):
        os.makedirs("../Data/")
full_recipes.to_csv("../Data/full_recipes.csv", index=False)
final_reviews_df.to_csv("../Data/user_interactions.csv", index=False)

In [231]:
display(pd.read_csv('../Data/full_recipes.csv'))

,name,id,minutes,contributor_id,nutrition,n_steps,steps,ingredients,n_ingredients
0,Tuna Kabobs,99998,25,Lorac,"['219.5', '7233', '8.112', '1.99', '53.917', '...",4,"['Preheat grill to medium high.', 'Combine soy...","['soy sauce', 'rice vinegar', 'toasted sesame ...",7
1,South Beach Diet Balsamic Vinaigrette,99996,5,papergoddess,"['142.7', '12991', '14.422', '29', '00', '120....",3,['Combine all ingredients in a jar or containe...,"['extra virgin olive oil', 'balsamic vinegar',...",6
2,All to Myself Cheesecake,99995,45,Claudia Dawn,"['268.5', '16963', '18.828', '9.748', '72.724'...",7,"['Beat cream cheese, sugar, vanilla and eggs t...","['reo cookies tops separated from bottoms', 'c...",7
3,Feta Potatoes,99994,45,Dawnab,"['264.3', '12648', '14.121', '7.838', '43.614'...",3,"['Preheat oven to 375.', 'combine all ingredie...",['frozen cubed hash brown potatoes southern st...,5
4,Shish Kabob Marinade,99992,125,jenjill,"['75.8', '01', '0.10', '00', '00', '117348', '...",4,"['Mix all ingredients together.', 'Add meat (c...","['soy sauce', 'ketchup', 'sugar', 'ginger', 'g...",5
...,...,...,...,...,...,...,...,...,...
583305,Myrna's Toasted Coconut-Chocolate Bars,618334,50,Unknown,[],2,['Heat the oven to 350 degrees F. Mix the suga...,"['heaping sugar', 'scant egg whites from abou...",5
583306,Mystery Meat Loaf,618335,100,Unknown,[],1,['Preheat oven to 350 degrees. In a large bowl...,"['pounds ground round beef percent lean', 'se...",7
583307,Mystery Mocha Cake,618336,60,Unknown,[],2,"['Preheat oven to 350 degrees F.', 'Melt the c...","['unsweetened chocolate', 'butter', 'sugar', '...",11
583308,Mystery Rolls,618337,20,Unknown,[],4,"['Preheat the oven to 350 degrees F.', 'Put th...","['stick butter', 'crumbled blue cheese', 'fl...",3
583309,Mystery of the Orient,618338,240,Unknown,[],3,['Make the base: Use flexible aluminum strips ...,"['pounds bittersweet chocolate, tempered', 'wh...",7

In [232]:
display(pd.read_csv('../Data/user_interactions.csv'))

,user_id,recipe_id,date,rating,review
0,1509050,99998.0,2022-01-01T00:00:00+00:00,5.0,"Substituted cayenne for wasabi, which we hate...."
1,672182,99998.0,2022-01-01T00:00:00+00:00,5.0,Wow - what a great & easy recipe to add to you...
2,983557,99996.0,2022-01-01T00:00:00+00:00,5.0,I tripled this recipe so id have it on hand fo...
3,1402541,99996.0,2022-01-01T00:00:00+00:00,5.0,"My husband and I love this Recipe. BUT, when ..."
4,1114506,99996.0,2022-01-01T00:00:00+00:00,5.0,Simple. Fast. Healthy. Tasty.
...,...,...,...,...,...
1237696,198104,13238.0,2022-01-01T00:00:00+00:00,5.0,We drained 2 cans of mixed vegetables in place...
1237697,198105,13238.0,2022-01-01T00:00:00+00:00,4.0,I doubled the spices (added curry powder) and ...
1237698,198106,13238.0,2022-01-01T00:00:00+00:00,3.0,Needs more flavor.
1237699,198107,13238.0,2022-01-01T00:00:00+00:00,5.0,Good stuff!
1237700,198108,13238.0,2022-01-01T00:00:00+00:00,4.0,"Love the diced little potatoes, they really ma..."